[workspace]
members = [
    "pandora_core",
    "pandora_protocols",
    "pandora_tools",
    "pandora_uniffi",
    "pandora_error",
    "integration_tests", "pandora_orchestrator", "pandora_cwm", "pandora_mcg",
]
resolver = "2"
