[workspace]
members = [
    "pandora_core",
    "pandora_protocols",
    "pandora_tools",
    "pandora_uniffi",
    "pandora_error",
    "integration_tests", "pandora_orchestrator", "pandora_cwm", "pandora_mcg", "pandora_sie", "pandora_learning_engine",
]
resolver = "2"
