[target.'cfg(all())']
rustflags = [
    "-D", "warnings",
    "-A", "clippy::result_large_err",
]

[build]
rustflags = ["-C", "instrument-coverage"]

[alias]
cov = "llvm-cov"
cov-report = "llvm-cov --html --output-dir coverage"
cov-test = "llvm-cov --workspace --all-features --html --output-dir coverage"


